//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountGJ
    {
        public int idx { get; set; }
        public Nullable<int> GLIdx { get; set; }
        public Nullable<int> tranTypeIdx { get; set; }
        public Nullable<int> userIdx { get; set; }
        public Nullable<int> vendorIdx { get; set; }
        public Nullable<int> employeeIdx { get; set; }
        public Nullable<int> customerIdx { get; set; }
        public Nullable<int> coaIdx { get; set; }
        public string invoiceNo { get; set; }
        public Nullable<decimal> debit { get; set; }
        public Nullable<decimal> credit { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string modifiedDate { get; set; }
    }
}
