//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountMasterGL
    {
        public int idxx { get; set; }
        public Nullable<int> tranTypeIdx { get; set; }
        public Nullable<int> userIdx { get; set; }
        public Nullable<int> vendorIdx { get; set; }
        public Nullable<int> employeeIdx { get; set; }
        public Nullable<int> customerIdx { get; set; }
        public string invoiceNoIdx { get; set; }
        public Nullable<decimal> debit { get; set; }
        public Nullable<decimal> credit { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string modifiedDate { get; set; }
        public Nullable<decimal> paidAmount { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<int> isCredit { get; set; }
        public Nullable<int> creditDays { get; set; }
        public Nullable<int> visible { get; set; }
        public Nullable<int> paymentModeIdx { get; set; }
        public Nullable<int> bankIdx { get; set; }
        public string chequeNumber { get; set; }
        public string memo { get; set; }
    }
}
