//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class advanceSalary
    {
        public int idx { get; set; }
        public Nullable<int> employeeIdx { get; set; }
        public Nullable<decimal> netSalary { get; set; }
        public Nullable<decimal> advanceAmount { get; set; }
        public string deductionMonth { get; set; }
        public string deductionYear { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<int> createdByUserIdx { get; set; }
        public string lastModificationDate { get; set; }
        public Nullable<int> lastModifiedByUserIdx { get; set; }
        public Nullable<int> visible { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> statusBy { get; set; }
        public string statusDate { get; set; }
        public Nullable<int> isExpire { get; set; }
        public Nullable<int> isPaid { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Balance { get; set; }
    }
}
