//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartofAccountsSubHead
    {
        public int idx { get; set; }
        public int headIdx { get; set; }
        public string subHeadName { get; set; }
        public string subHeadCode { get; set; }
        public System.DateTime creationDate { get; set; }
        public int createdByUserIdx { get; set; }
        public string lasModificationDate { get; set; }
        public int lastModifiedByUserIdx { get; set; }
        public int visible { get; set; }
    }
}
