
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SMSYSTEM
{

using System;
    using System.Collections.Generic;
    
public partial class COA
{

    public int idx { get; set; }

    public Nullable<int> parentIdx { get; set; }

    public Nullable<int> headAccount { get; set; }

    public string accountName { get; set; }

    public Nullable<int> CoaLevel { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
