//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class companyBank
    {
        public int idx { get; set; }
        public Nullable<int> bankIdx { get; set; }
        public string accountTitle { get; set; }
        public string Branch { get; set; }
        public string accountNumber { get; set; }
        public System.DateTime creationDate { get; set; }
        public int createdByUserIdx { get; set; }
        public string visible { get; set; }
        public string lastModificationDate { get; set; }
        public Nullable<int> lastModifiedByUserIdx { get; set; }
    }
}
