//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumption
    {
        public int idx { get; set; }
        public Nullable<int> itemIdx { get; set; }
        public Nullable<int> consumedBy { get; set; }
        public Nullable<decimal> consumedQuanity { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<int> createdByUserIdx { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> statusBy { get; set; }
        public string statusDate { get; set; }
        public string remarks { get; set; }
        public Nullable<int> lastModificationByUserIdx { get; set; }
        public string lastModificationDate { get; set; }
        public Nullable<int> visible { get; set; }
        public Nullable<decimal> stock { get; set; }
    }
}
