
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SMSYSTEM
{

using System;
    using System.Collections.Generic;
    
public partial class contract
{

    public int idx { get; set; }

    public Nullable<int> empCode { get; set; }

    public Nullable<int> employeeIdx { get; set; }

    public Nullable<int> departmentIdx { get; set; }

    public Nullable<int> designationIdx { get; set; }

    public Nullable<int> employeeTypeIdx { get; set; }

    public Nullable<int> contractTypeIdx { get; set; }

    public string contractStartDate { get; set; }

    public string contractEndDate { get; set; }

    public Nullable<System.DateTime> creationDate { get; set; }

    public Nullable<int> createdByUserIdx { get; set; }

    public string lastModificationDate { get; set; }

    public Nullable<int> lastModifiedByUserIdx { get; set; }

    public Nullable<int> visible { get; set; }

}

}
