//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int idx { get; set; }
        public Nullable<int> hrmsNumber { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string cnic { get; set; }
        public string dateOfBirth { get; set; }
        public string contactNumber { get; set; }
        public Nullable<int> maritalIdx { get; set; }
        public Nullable<int> genderIdx { get; set; }
        public string emailAddress { get; set; }
        public string address { get; set; }
        public Nullable<int> departmentIdx { get; set; }
        public Nullable<int> designationIdx { get; set; }
        public string hiringDate { get; set; }
        public string avatar { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<int> isTerminated { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<int> createdByUserIdx { get; set; }
        public string lastModificationDate { get; set; }
        public Nullable<int> lastModifiedByUserIdx { get; set; }
        public Nullable<int> visible { get; set; }
    }
}
