//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryDetail
    {
        public int Idx { get; set; }
        public Nullable<int> InventoryIdx { get; set; }
        public Nullable<int> PurchaseDetailidx { get; set; }
        public Nullable<int> ConsumptionIdx { get; set; }
    }
}
