//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public int idx { get; set; }
        public Nullable<int> productIdx { get; set; }
        public Nullable<decimal> stock { get; set; }
        public Nullable<int> productTypeIdx { get; set; }
        public Nullable<decimal> unitPrice { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public System.DateTime creationDate { get; set; }
    }
}
