//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanInstallment
    {
        public int idx { get; set; }
        public Nullable<int> loanIdx { get; set; }
        public Nullable<int> loanAmount { get; set; }
        public Nullable<int> numberOfInstallment { get; set; }
        public Nullable<int> installmentAmount { get; set; }
        public Nullable<int> status { get; set; }
    }
}
