
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SMSYSTEM
{

using System;
    using System.Collections.Generic;
    
public partial class paymentMode
{

    public int idx { get; set; }

    public string paymentMode1 { get; set; }

}

}
