//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class payroll
    {
        public int idx { get; set; }
        public Nullable<int> departmentIdx { get; set; }
        public Nullable<int> empIdx { get; set; }
        public Nullable<decimal> netSalary { get; set; }
        public Nullable<int> totalLeave { get; set; }
        public Nullable<decimal> leaveDeductionAmount { get; set; }
        public Nullable<decimal> loanReamainingAmount { get; set; }
        public Nullable<decimal> loanDeductionAmount { get; set; }
        public Nullable<decimal> advanceRemainingAmount { get; set; }
        public Nullable<decimal> advanceDeductionAmount { get; set; }
        public Nullable<decimal> otherBenefits { get; set; }
        public Nullable<decimal> totalSalary { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<int> createdByUserrIDx { get; set; }
        public string lastModificationDate { get; set; }
        public Nullable<int> lastModifiedByUserIdx { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> statusBy { get; set; }
        public string statusDate { get; set; }
        public Nullable<int> visible { get; set; }
    }
}
