
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SMSYSTEM
{

using System;
    using System.Collections.Generic;
    
public partial class planner
{

    public int ID { get; set; }

    public string TO_DO { get; set; }

    public System.DateTime TO_DO_Date { get; set; }

    public System.DateTime DateCreated { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<bool> status { get; set; }

}

}
