
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SMSYSTEM
{

using System;
    using System.Collections.Generic;
    
public partial class pruchaseDetail
{

    public int idx { get; set; }

    public Nullable<int> purchaseIdx { get; set; }

    public int productTypeIdx { get; set; }

    public Nullable<int> itemIdx { get; set; }

    public Nullable<decimal> unitPrice { get; set; }

    public Nullable<decimal> qty { get; set; }

    public Nullable<decimal> amount { get; set; }

    public Nullable<System.DateTime> creationDate { get; set; }

    public Nullable<int> createdByUserIdx { get; set; }

    public string lastModificationDate { get; set; }

    public Nullable<int> lastModifiedByUserIdx { get; set; }

    public Nullable<int> visible { get; set; }

    public Nullable<System.DateTime> DueDate { get; set; }

}

}
