
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SMSYSTEM
{

using System;
    using System.Collections.Generic;
    
public partial class Role
{

    public int idx { get; set; }

    public Nullable<int> employeeIdx { get; set; }

    public string pageUrl { get; set; }

    public Nullable<bool> add { get; set; }

    public Nullable<bool> edit { get; set; }

    public Nullable<bool> delete { get; set; }

    public Nullable<bool> view { get; set; }

    public Nullable<bool> approved { get; set; }

    public Nullable<System.DateTime> creationDate { get; set; }

    public Nullable<int> createdByUserIdx { get; set; }

    public string lastModificationDate { get; set; }

    public Nullable<int> lastModifiedByUserIdx { get; set; }

    public Nullable<int> visible { get; set; }

}

}
