
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SMSYSTEM
{

using System;
    using System.Collections.Generic;
    
public partial class salary
{

    public int idx { get; set; }

    public Nullable<int> empIdx { get; set; }

    public Nullable<int> basicSalary { get; set; }

    public Nullable<int> hraAllowance { get; set; }

    public Nullable<int> daAllowance { get; set; }

    public Nullable<int> conveyance { get; set; }

    public Nullable<int> medicalAllowance { get; set; }

    public Nullable<int> others { get; set; }

    public Nullable<int> netSalary { get; set; }

    public Nullable<int> isActive { get; set; }

    public Nullable<System.DateTime> creationDate { get; set; }

    public Nullable<int> createdByUserIdx { get; set; }

    public string lastModificationDate { get; set; }

    public Nullable<int> lastModifiedByUserIdx { get; set; }

    public Nullable<int> visible { get; set; }

}

}
