
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SMSYSTEM
{

using System;
    using System.Collections.Generic;
    
public partial class service
{

    public int idx { get; set; }

    public string serviceName { get; set; }

    public string serviceCode { get; set; }

    public Nullable<int> unitIdx { get; set; }

    public string serviceCost { get; set; }

    public string description { get; set; }

    public Nullable<System.DateTime> creationDate { get; set; }

    public Nullable<int> createdByUserIdx { get; set; }

    public string lastModificationDate { get; set; }

    public Nullable<int> lastModifiedByUserIdx { get; set; }

    public Nullable<int> visible { get; set; }

}

}
