//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class station
    {
        public int idx { get; set; }
        public string stationName { get; set; }
        public string address { get; set; }
        public string contactNumber { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<int> createdByUserIdx { get; set; }
        public string lastModificationDate { get; set; }
        public Nullable<int> lastModifiedByUserIdx { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<int> visible { get; set; }
    }
}
