//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int idx { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string CNIC { get; set; }
        public string cellNumber { get; set; }
        public string email { get; set; }
        public Nullable<int> designationIdx { get; set; }
        public Nullable<int> departmentIdx { get; set; }
        public string loginId { get; set; }
        public string password { get; set; }
        public Nullable<int> gender { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<int> createdByUserIdx { get; set; }
        public string lastModificationDate { get; set; }
        public Nullable<int> lastModifiedByUserIdx { get; set; }
        public int isActive { get; set; }
        public int visible { get; set; }
        public string passCode { get; set; }
        public Nullable<int> PascodeYNID { get; set; }
        public Nullable<bool> Is_Admin { get; set; }
    }
}
