
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SMSYSTEM
{

using System;
    using System.Collections.Generic;
    
public partial class vendor
{

    public int idx { get; set; }

    public string vendorName { get; set; }

    public string vendorCode { get; set; }

    public string contactPersonName { get; set; }

    public Nullable<int> vendorAccountType { get; set; }

    public string accountNo { get; set; }

    public string contact { get; set; }

    public string emailAddress { get; set; }

    public string strn { get; set; }

    public string ntn { get; set; }

    public string address { get; set; }

    public string description { get; set; }

    public Nullable<System.DateTime> creationDate { get; set; }

    public Nullable<int> createdByUserIdx { get; set; }

    public string lastModificationDate { get; set; }

    public Nullable<int> lastModifiedByUserIdx { get; set; }

    public Nullable<int> visible { get; set; }

    public Nullable<decimal> openingBalance { get; set; }

}

}
