
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SMSYSTEM
{

using System;
    using System.Collections.Generic;
    
public partial class loan
{

    public int idx { get; set; }

    public Nullable<int> empIdx { get; set; }

    public Nullable<decimal> loanAmount { get; set; }

    public Nullable<int> numberOfInstallment { get; set; }

    public Nullable<decimal> installmentAmount { get; set; }

    public Nullable<int> modeOfPayment { get; set; }

    public string loanReqDate { get; set; }

    public string endDate { get; set; }

    public string purposeOfLoan { get; set; }

    public Nullable<int> status { get; set; }

    public Nullable<int> statusBy { get; set; }

    public Nullable<System.DateTime> statusDate { get; set; }

    public string remarks { get; set; }

    public Nullable<System.DateTime> creationDate { get; set; }

    public Nullable<int> createdByUserIdx { get; set; }

    public string lastModificationDate { get; set; }

    public Nullable<int> lastModifiedByUserIdx { get; set; }

    public Nullable<int> visible { get; set; }

    public Nullable<decimal> balance { get; set; }

    public Nullable<decimal> paid { get; set; }

    public Nullable<int> isPaid { get; set; }

    public Nullable<int> isExpire { get; set; }

}

}
