
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SMSYSTEM
{

using System;
    using System.Collections.Generic;
    
public partial class TblGatePass
{

    public int idx { get; set; }

    public int saleID { get; set; }

    public string drivername { get; set; }

    public string numberplate { get; set; }

    public Nullable<System.DateTime> createddate { get; set; }

    public Nullable<int> userid { get; set; }

    public Nullable<bool> status { get; set; }

}

}
